### IMPORTANT, THIS IMAGE CAN ONLY BE RUN IN LINUX DOCKER
### You will run into a segfault in mac
FROM python:3.11.6-slim-bookworm as base

# Install poetry
RUN pip install pipx
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"

# Dependencies to build llama-cpp
RUN apt update && apt install -y \
  libopenblas-dev\
  ninja-build\
  build-essential\
  pkg-config\
  wget\
  make

# https://python-poetry.org/docs/configuration/#virtualenvsin-project
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/worker/app
COPY . .
RUN poetry install --with local
RUN poetry install --with ui

# Run the setup script
RUN poetry run python scripts/setup

FROM base as app

ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080

RUN adduser --system worker
WORKDIR /home/worker/app

# Copy everything from the 'dependencies' stage
COPY --from=dependencies /home/worker/app/ ./

# Set necessary environment variables
ENV PATH="/root/.local/bin:$PATH"
ENV PGPT_PROFILES=local

USER root
ENTRYPOINT ["make", "run"]